csevent/codetreasure/urls.py
from django.urls import path
from .views import *

app_name = 'codetreasure'


urlpatterns = [
    #  Prelims
    path('prelims/', prelm_question, name='prelims'),
    path('prelims/status/', last_question_prelims, name='last_question_prelims'),
    path('final/status/',last_question_final,name='last_question_final'),
    #  Finals
    # Code Shuffle
    path('finals/codeshuffle/', final_code_shuffle_function,
         name='final_code_shuffle_function'),
    # Spot Error
    path('finals/spoterror/', final_spot_error_function,
         name='final_spot_error_function'),
    # Binary Hunt
    path('finals/binaryhunt/', final_binary_function,
         name='final_binary_function'),
    #cheated url path :
    path('cheated/prelims/',exit_test_preliminary,name='exit_test_preliminary'),
    path('cheated/final/',exit_test_final,name='exit_test_final'),
]

csevent/csevent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .views import *


urlpatterns = [
    path('verification/', include('verify_email.urls'), name='verification'),
    path('admin/', admin.site.urls),
    path('', homepage, name="homepage"),
    path('accounts/', include('userapp.urls')),
    path('events/codetreasure/', include('codetreasure.urls')),
    path('events/ransack/', include('wordhunt.urls')),
    path('events/', include('imageupload.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

csevent/codetreasure/models.py
from django.db import models
from userapp.models import User


class question_model(models.Model):
    question = models.CharField(max_length=450)
    option_A = models.CharField(max_length=30)
    option_B = models.CharField(max_length=30)
    option_C = models.CharField(max_length=30)
    option_D = models.CharField(max_length=30)
    correct_option = models.CharField(max_length=30)

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = 'Prelims Aptitude Question'


class Stud_Res_CodeTreasure_Prelm(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    question = models.ForeignKey(question_model, on_delete=models.CASCADE)
    user_answer = models.CharField(max_length=30)
    status = models.BooleanField()
    when = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Student Result Prelim'


# final round code shuffling
class final_code_shuffle(models.Model):
    image = models.ImageField(upload_to='final_code_shuffle/')

    class Meta:
        verbose_name = 'Code Shuffle Image'


class final_code_shuffle_relation(models.Model):
    question = models.ManyToManyField(final_code_shuffle)
    ques_no = models.CharField(max_length=80, default="Codeshuffle")

    def __str__(self):
        return self.ques_no

    class Meta:
        verbose_name = 'Code Shuffle Question'


# Final round binary
class final_code_binary_question(models.Model):
    question = models.CharField(max_length=250)
    ques_no = models.CharField(max_length=80, default="Binaryhunt")

    def __str__(self):
        return self.ques_no

    class Meta:
        verbose_name = 'Binary Hunter Question'


# Final round spot the error
class final_code_spot_error_image(models.Model):
    image = models.ImageField(upload_to="final_code_spot_error/")

    class Meta:
        verbose_name = 'Spot Error Image'


class final_code_spot_error_question(models.Model):
    question = models.ManyToManyField(final_code_spot_error_image)
    ques_no = models.CharField(max_length=80, default="SpotError")

    def __str__(self):
        return self.ques_no

    class Meta:
        verbose_name = 'Spot Error Question'


# Final round question's relation with the user's answer
class final_answer_relation(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    final_code_shuffle_question = models.ForeignKey(
        final_code_shuffle_relation, on_delete=models.CASCADE, null=True)
    final_code_binary_question = models.ForeignKey(
        final_code_binary_question, on_delete=models.CASCADE, null=True)
    final_code_spot_error_question = models.ForeignKey(
        final_code_spot_error_question, on_delete=models.CASCADE, null=True)
    user_answer = models.TextField()
    when = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Student Result Final'


class Score_codetreasureModel(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    roundtype_choice = (('prelims', 'Prelims'), ('final', 'Finals'))
    roundtype = models.CharField(max_length=8, choices=roundtype_choice)
    score = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = 'Score'

csevent/codetreasure/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import *
from userapp.models import test_timings,prelim_test,final_test
import datetime

def prelm_question(request):
    #Event actual timings(date and time)
    date_obj=get_object_or_404(test_timings,event="codetreasure",round_type="preliminary")
    start=date_obj.start
    end=date_obj.end
    if request.method == "POST": 
        student = request.user
        q_id = request.POST.get('q_id', 'something wrong')
        question = get_object_or_404(question_model, id=q_id)
        if Stud_Res_CodeTreasure_Prelm.objects.filter(student=student, question=question).exists():
            return JsonResponse({'save': "something wrong"})
        else:
            user_answer = request.POST.get("answer", "No value")
            if user_answer == question.correct_option:
                status = True
            else:
                status = False
            
            #Before sumitting the answer this if checks whether the time exceeds or not
            current_time_during_submit=datetime.datetime.now()
            if start<=current_time_during_submit and current_time_during_submit<=end:
                #Checking for cheated
                current_user_obj=get_object_or_404(prelim_test,Student=request.user,event='codetreasure')
                if current_user_obj.test_status=='cheated':
                   return JsonResponse({'save':'cheated'})
                else:
                    Stud_Res_CodeTreasure_Prelm.objects.create(
                        student=student, question=question, user_answer=user_answer, status=status)
                    return JsonResponse({'save': "completed"})
            else: 
                return JsonResponse({'save':'after'})
    
    else:
        #Current date and time
        current=datetime.datetime.now()
        if start>current:
            return render(request,'show_test.html',{'start':start,'end':end,'status':'before'})
            #status = True indicates test still exist
        elif start<=current and current<=end:
            current_user_obj=get_object_or_404(prelim_test,Student=request.user,event='codetreasure')
            #Update prelim_test model for the particular user
            if current_user_obj.test_status=="not_started":
                prelim_test.objects.filter(Student=request.user,event='codetreasure').update(start=datetime.datetime.now(),test_status='started',attended=True)
            elif current_user_obj.test_status=="cheated":
                return render(request,'show_test.html',{'status':'cheated'})

            page_no = request.GET.get('page', 1)
            question_set = question_model.objects.all().order_by('id')
            pages = Paginator(question_set, 1)

            try:
               page = pages.page(page_no)
            except EmptyPage:
               page = pages.page(pages.num_pages)
            except PageNotAnInteger:
               page = pages.page(1)

            context = {
            'page': page, 'pages': pages
            }
            return render(request, 'codetreasure/prelm_question.html', context=context)
        elif end<current:
            #test = after indicates test has completed already
            return render(request,'show_test.html',{'start':start,'end':end,'status':'after'})
        else:
            return HttpResponse("something wrong sorry for the inconvenience")

        


def final_code_shuffle_function(request):
    #Event actual timings(date and time)
    date_obj=get_object_or_404(test_timings,event="codetreasure",round_type="final")
    start=date_obj.start
    end=date_obj.end
    
    if request.method == "POST":
        student = request.user
        question = get_object_or_404(
            final_code_shuffle_relation, id=request.POST.get('q_id', 'something wrong'))
        
        #Checks whether this question is already entered by the user
        if final_answer_relation.objects.filter(student=student, final_code_shuffle_question=question).exists():
            return JsonResponse({'result': "already entered"})
        
        else:
            user_answer = request.POST.get('answer', 'Something wrong')
            
            #Checks whether the time is exhausted or not before submitting the answers
            current_time_during_submit=datetime.datetime.now()
            if start<=current_time_during_submit and current_time_during_submit<=end:
                current_user_obj=get_object_or_404(final_test,student=request.user,event='codetreasure')
                if current_user_obj.test_status=='cheated':
                    return JsonResponse({'result':'cheated'})
                else:
                    obj = final_answer_relation.objects.create(
                            student=student, final_code_shuffle_question=question, user_answer=user_answer)
                    return JsonResponse({'result': "completed"})
            else: 
                return JsonResponse({'result':'after'})

    else:
        #Current time the finalists clicked the event
        current=datetime.datetime.now()
        #Checking if they before start the test
        if start>current:
            return render(request,'show_test.html',{'start':start,'end':end,'status':'before'})
        
        elif start<=current and current<=end:
            current_user_obj=get_object_or_404(final_test,student=request.user,event='codetreasure')
            #Update final_test model for the particular user
            if current_user_obj.test_status=="not_started":
                final_test.objects.filter(student=request.user,event='codetreasure').update(start=datetime.datetime.now(),test_status='started',attended=True)
            elif current_user_obj.test_status=="cheated":
                return render(request,'show_test.html',{'status':'cheated'})

            page_no = request.GET.get('page', 1)
            question_set = final_code_shuffle_relation.objects.all().order_by('id')
            pages = Paginator(question_set, 1)
             
            try:
               page = pages.page(page_no)
            except EmptyPage:
               page = pages.page(pages.num_pages)
            except PageNotAnInteger:
                page = pages.page(1)

            context = {
                'page': page, 'pages': pages
            }

            return render(request, 'codetreasure/final_code_shuffle.html', context=context)
        elif end<current:
            #test = after indicates test has completed already
            return render(request,'show_test.html',{'start':start,'end':end,'status':'after'})
        else:
            return HttpResponse("something wrong sorry for the inconvenience")


def final_binary_function(request):
    #Event actual timings(date and time)
    date_obj=get_object_or_404(test_timings,event="codetreasure",round_type="final")
    start=date_obj.start
    end=date_obj.end

    if request.method == "POST":
        student = request.user
        question = get_object_or_404(
            final_code_binary_question, id=request.POST.get('q_id', 'something wrong'))
        if final_answer_relation.objects.filter(student=student, final_code_binary_question=question).exists():
            return JsonResponse({'result': 'already entered'})
        else:
            user_answer = request.POST.get('answer', 'something wrong')
            current_time_during_submit=datetime.datetime.now()
            if start<=current_time_during_submit and current_time_during_submit<=end:
                current_user_obj=get_object_or_404(final_test,student=request.user,event='codetreasure')
                if current_user_obj.test_status=='cheated':
                    return JsonResponse({'result':'cheated'})
                else:
                    final_answer_relation.objects.create(
                        student=student, final_code_binary_question=question, user_answer=user_answer)
                    return JsonResponse({'result': 'completed'})
            else:
                return JsonResponse({'result':'after'})
            
    else:
        #Current time the finalists clicked the event
        current=datetime.datetime.now()
        #Checking if they before start the test
        if start>current:
            return render(request,'show_test.html',{'start':start,'end':end,'status':'before'})
        elif start<=current and current<=end:
            current_user_obj=get_object_or_404(final_test,student=request.user,event='codetreasure')
            #Update final_test model for the particular user
            if current_user_obj.test_status=="not_started":
                final_test.objects.filter(student=request.user,event='codetreasure').update(start=datetime.datetime.now(),test_status='started',attended=True)
            elif current_user_obj.test_status=="cheated":
                return render(request,'show_test.html',{'status':'cheated'})
            page_no = request.GET.get('page', 1)
            question_set = final_code_binary_question.objects.all().order_by('id')
            pages = Paginator(question_set, 1)

            try:
               page = pages.page(page_no)
            except EmptyPage:
               page = pages.page(pages.num_pages)
            except PageNotAnInteger:
               page = pages.page(1)

            return render(request, 'codetreasure/final_binary.html', {'page': page, 'pages': pages})
        elif end<current:
            #test = False indicates test has completed already
            return render(request,'show_test.html',{'start':start,'end':end,'status':'after'})
        else:
            return HttpResponse("something wrong sorry for the inconvenience")


def final_spot_error_function(request):
    #Event actual timings(date and time)
    date_obj=get_object_or_404(test_timings,event="codetreasure",round_type="final")
    start=date_obj.start

csevent/templates/codetreasure/final_binary.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>{{page}}</h2>
<div id="binary-table">
    <img src="{% static 'img/binary.jpg' %}">
</div>
{% for p in page.object_list %}
<h2>Question 1 :</h2>
<h4>{{p.question}}</h4>

<input type="text" class="form-control" placeholder="Enter your answers here...">
<button class="btn btn-success float-right submit_button" data-question="{{p.id}}">Submit</button>

{% if page.has_next %}
<a href="?page={{page.next_page_number}}" class="btn btn-primary float-right next"
    style="pointer-events: none;cursor:default;">Next</a>
{% else %}
<a href="{% url 'codetreasure:final_spot_error_function' %}" class="btn btn-primary float-right next"
    style="pointer-events:none;cursor:default">Next</a>
{% endif %}
{% endfor %}

{% endblock %}
{% block script %}
<script>
    $(document).ready(function () {
        setTimeout(function(){
            $("#binary-table").addClass('d-none');
        },5000)
        var count = 0

        $(window).focus(function () {
            count = count + 1
            if (count === 1) {
                alert("Tab Switching is not Allowed more than 2 times.\nTab Switch Count: 1");
            }
            else if (count === 2) {
                alert("Tab Switching is not Allowed more than 2 times.\nTab Switch Count: 2");
            }
            else {
                alert("Malpractice!!!!!!");
                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'codetreasure:exit_test_final' %}",
                    type: 'post',
                    success: function (data) {
                        if (data.is_taken) {
                            location.reload()
                        }
                    }
                });
            }
        });

        $(".submit_button").click(function () {
            //Question id
            var q_id = $(this).attr('data-question')
            //answer
            var answer = $(this).prev().val()
            if (answer.length == 0) {
                alert("Please fill the answer otherwise you can't go to the next page")
            }
            else {
                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'codetreasure:final_binary_function' %}",
                    type: 'post',
                    data: { 'answer': answer, 'q_id': q_id },
                    dataType: 'json',
                    success: function (data) {
                        if (data['result'] == "already entered") {
                            alert("You have already attended this question");
                            $('.next').removeAttr("style")
                        }
                        else if(data['result']=='after'){
                            alert("Time is over")
                            $('.next').removeAttr("style")
                        }
                        else if(data['result']=='cheated'){
                            alert('Malpractice')
                            $('.next').removeAttr("style")
                        }
                        else if (data['result'] == "completed") {
                            alert("Submitted successfully")
                            $('.next').removeAttr("style")
                        }
                    }
                });
            }

        });
    });
</script>
{% endblock %}

csevent/templates/codetreasure/final_code_shuffle.html
{% extends 'base.html' %}
{% block content %}
<h3>
    Consider the given program, guess it and arrange the shuffled parts to get a proper code:
</h3>

<h2>{{page}}</h2>

{% for p in page.object_list %}
<h2>Question 1 :</h2>

{% for q1 in p.question.all %}
<img src="{{q1.image.url}}">
{% endfor %}

<input type="text" class="form-control" placeholder="Enter your answers here...">
<button class="btn btn-success float-right submit_button" data-question="{{p.id}}">Submit</button>
{% if page.has_next %}
<a href="?page={{page.next_page_number}}" class="btn btn-primary float-right next"
    style="pointer-events: none;cursor:default;">Next</a>
{% else %}
<a href="{% url 'codetreasure:final_binary_function' %}" class="btn btn-primary float-right next"
    style="pointer-events:none;cursor:default">Next</a>
{% endif %}
{% endfor %}

{% endblock %}


{% block script %}
<script>
    $(document).ready(function () {

        var count = 0

        $(window).focus(function () {
            count = count + 1

            if (count === 1) {
                alert("Tab Switching is not Allowed more than 2 times.\nTab Switch Count: 1");
            }
            else if (count === 2) {
                alert("Tab Switching is not Allowed more than 2 times.\nTab Switch Count: 2");
            }
            else {
                alert("Malpractice!!!!!!");
                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'codetreasure:exit_test_final' %}",
                    type: 'post',
                    success: function (data) {
                        if (data.is_taken) {
                            location.reload();
                        }
                    }
                });
            }
        });

        $(".submit_button").click(function () {
            //Question id
            var q_id = $(this).attr('data-question')
            //Answer id
            var answer = $(this).prev().val()
            if (answer.length == 0) {
                alert("Please fill the answer otherwise you can't go to the next page")
            }
            else {
                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'codetreasure:final_code_shuffle_function' %}",
                    type: 'post',
                    data: { 'answer': answer, 'q_id': q_id },
                    dataType: 'json',
                    success: function (data) {
                        if (data['result'] == "already entered") {
                            alert("You have already attended this question");
                            $('.next').removeAttr("style")
                        }
                        else if(data['result']=='after'){
                            alert("Time is over")
                            $('.next').removeAttr("style")
                            //window.close()
                        }
                        else if(data['result']=='cheated'){
                            alert('malpractice')
                            $('.next').removeAttr("style")
                        }
                        else if (data['result'] == "completed") {
                            alert("Submitted successfully")
                            $('.next').removeAttr("style")
                        }
                    }
                });
            }

        });
    });
</script>
{% endblock %}

csevent/templates/codetreasure/final_spot_error.html
{% extends 'base.html' %}
{% block content %}

<h2>{{page}}</h2>


{% for p in page.object_list %}
<h2>Question 1 :</h2>

{% for q1 in p.question.all %}
<img src="{{q1.image.url}}" alt="img" width="500">
{% endfor %}

<textarea rows="10" placeholder="Enter the spotted lines" class="form-control"></textarea>
<button class="btn btn-success float-right submit_button" data-question="{{p.id}}">Submit</button>
{% if page.has_next %}
<a href="?page={{page.next_page_number}}" class="btn btn-primary float-right next"
    style="pointer-events: none;cursor:default;">Next</a>
{% else %}
<a href="{% url 'codetreasure:last_question_final' %}" class="btn btn-primary float-right next"
    style="pointer-events:none;cursor:default">Next</a>
{% endif %}
{% endfor %}

{% endblock %}
{% block script %}
<script>
    $(document).ready(function () {

        var count = 0

        $(window).focus(function () {
            count = count + 1
            if (count === 1) {
                alert("Tab Switching is not Allowed more than 2 times.\nTab Switch Count: 1");
            }
            else if (count === 2) {
                alert("Tab Switching is not Allowed more than 2 times.\nTab Switch Count: 2");
            }
            else {
                alert("Exam Over!!!!!!");
                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'codetreasure:exit_test_final' %}",
                    type: 'post',
                    success: function (data) {
                        if (data.is_taken) {
                            location.reload();
                        }
                    }
                });
            }
        });

        $(".submit_button").click(function () {
            //Question id
            var q_id = $(this).attr('data-question')
            //Answer
            var answer = $(this).prev().val()
            if (answer.length == 0) {
                alert("Please fill the answer otherwise you can't go to the next page")
            }
            else {
                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'codetreasure:final_spot_error_function' %}",
                    type: 'post',
                    data: { 'answer': answer, 'q_id': q_id },
                    dataType: 'json',
                    success: function (data) {
                        if (data['result'] == "already entered") {
                            alert("You have already attended this question");
                            $('.next').removeAttr("style")
                        }
                        else if(data['result']=='after'){
                            alert('Time is over')
                            $('.next').removeAttr("style")
                        }
                        else if(data['result']=='cheated'){
                            alert("You have done a malpractice")
                            $('.next').removeAttr("style")
                        }
                        else if (data['result'] == "completed") {
                            alert("Submitted successfully")
                            $('.next').removeAttr("style")
                        }
                    }
                });
            }

        });
    });
</script>
{% endblock %}

csevent/templates/codetreasure/prelm_question.html
{% extends 'base.html' %}
{% block content %}
<h2>{{page}}</h2>

{% for q in page.object_list %}
<p>{{q}}</p>
<form method="POST" action="#" class="{{q.id}}">
    {% csrf_token %}
    <div class="form-check">
        <label for="option-1" class="form-check-label">
            <input type="radio" class="form-check-input" id="option-1" name="{{q.id}}" value="{{q.option_A}}">
            {{q.option_A}}
        </label>
    </div>
    <div class="form-check">
        <label for="option-2" class="form-check-label">
            <input type="radio" class="form-check-input" id="option-2" name="{{q.id}}" value="{{q.option_B}}">
            {{q.option_B}}
        </label>
    </div>
    <div class="form-check">
        <label for="option-3" class="form-check-label">
            <input type="radio" class="form-check-input" id="option-3" name="{{q.id}}" value="{{q.option_C}}">
            {{q.option_C}}
        </label>
    </div>
    <div class="form-check">
        <label for="option-4" class="form-check-label">
            <input type="radio" class="form-check-input" id="option-4" name="{{q.id}}" value="{{q.option_D}}">
            {{q.option_D}}
        </label>
    </div>
</form>
<button type="button" class="btn btn-success float-right submit_button" data-question="{{q.id}}">Submit</button>
{% if page.has_next %}
<a href="?page={{page.next_page_number}}" class="btn btn-primary float-right next"
    style="pointer-events: none;cursor:default;">Next</a>
{% else %}
<a href="{% url 'codetreasure:last_question_prelims' %}" class="btn btn-primary float-right next"
    style="pointer-events:none;cursor:default">Next</a>
{% endif %}
{% endfor %}
{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {

        var count = 0

        $(window).focus(function () {
            count = count + 1
            if (count === 1) {
                alert("Tab Switching is not Allowed more than 2 times.\nTab Switch Count: 1");
            }
            else if (count === 2) {
                alert("Tab Switching is not Allowed more than 2 times.\nTab Switch Count: 2");
            }
            else {
                alert("Malpractice");
                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'codetreasure:exit_test_preliminary' %}",
                    type: 'post',
                    success: function (data) {
                        if (data.is_taken) {
                            location.reload();
                        }
                    }
                });
            }
        });

        $(".submit_button").click(function () {
            //Question id
            var q_id = $(this).attr('data-question')
            //Answer
            var answer = $("input[name=" + q_id + "]:checked").attr('value')
            if (answer.length == 0) {
                alert("Please fill the answer otherwise you can't go to the next page")
            }
            else{
                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'codetreasure:prelims' %}",
                    type: 'post',
                    data: { 'answer': answer, 'q_id': q_id },
                    dataType: 'json',
                    success: function (data) {
                        if (data['save'] == "something wrong") {
                            alert("You have already attended this question");
                            $('.next').removeAttr("style")
                        }
                        else if(data['save']=='after'){
                            alert('Test timing is over')
                            $('.next').removeAttr("style")
                            //Browser compatibility two close is used below
                            //window.close()
                            //close()
                        }
                        else if(data['save']=='cheated'){
                            alert('Malpractice')
                            $('.next').removeAttr("style")
                        }
                        else if (data['save'] == "completed") {
                            alert("Submitted successfully")
                            $('.next').removeAttr("style")
                        }
                    }
                });
            }
           
        });
    })
</script>
{% endblock %}