csevent/csevent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .views import *


urlpatterns = [
    path('verification/', include('verify_email.urls'), name='verification'),
    path('admin/', admin.site.urls),
    path('', homepage, name="homepage"),
    path('accounts/', include('userapp.urls')),
    path('events/codetreasure/', include('codetreasure.urls')),
    path('events/ransack/', include('wordhunt.urls')),
    path('events/', include('imageupload.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

csevent/wordhunt/urls.py
from django.urls import path
from .views import *

app_name = "wordhunt"

urlpatterns = [
    # Reteriving Q/A for Prelims & Finals
    path('prelims/sectionA/', question_prelims_sectionA, name="prelims"),
    path('prelims/sectionB/', question_prelims_sectionB, name="prelimsB"),
    path('finals/sectionA/', question_finals_sectionA, name="finals"),
    path('finals/sectionB/', question_finals_sectionB, name="finalsB"),
    # Answer Submission URl for Prelims & Finals
    path('prelims/submit_answer/', answer_submit, name="answer_submit_prelims"),
    # Cheated Prelims & Finals
    path('text/exit/', exit_test, name="exit_test"),
    # Test submitted
    path('finished_test/<int:id>/', finished_test, name="finished_test"),
]

csevent/wordhunt/models.py
from django.db import models
from userapp.models import User


class Images(models.Model):
    image = models.ImageField(upload_to="Wordhunt/")


# Question for WordHunt Prelims & Final
class Wordhunt(models.Model):
    images = models.ManyToManyField(Images)
    correct_answer = models.CharField(max_length=25)
    section_choice = (('A', 'A'), ('B', 'B'))
    section = models.CharField(max_length=1, choices=section_choice)
    roundtype_choice = (('prelims', 'Prelims'), ('final', 'Finals'))
    roundtype = models.CharField(max_length=8, choices=roundtype_choice)

    class Meta:
        verbose_name = 'Question'


# Student Result for WordHunt Prelims & Final
class Stud_Res_WordHunt(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Wordhunt, on_delete=models.CASCADE)
    user_answer = models.CharField(max_length=30)
    status = models.BooleanField()
    date_time = models.DateTimeField(auto_now_add=True)
    roundtype_choice = (('prelims', 'Prelims'), ('final', 'Finals'))
    roundtype = models.CharField(max_length=8, choices=roundtype_choice)

    class Meta:
        verbose_name = 'Student Result WordHunt'


class Score_wordhuntModel(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    roundtype_choice = (('prelims', 'Prelims'), ('final', 'Finals'))
    roundtype = models.CharField(max_length=8, choices=roundtype_choice)
    score = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = 'Score'

csevent/wordhunt/forms.py
from django import forms

from .models import *


class Student_Answer(forms.ModelForm):

    class Meta:
        model = Stud_Res_WordHunt
        fields = ['user_answer']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_answer'].widget.attrs.update(
            {'placeholder': 'Enter your answer'})
        self.fields['user_answer'].label = "Answer :"

csevent/wordhunt/views.py
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.http import JsonResponse
import datetime
from .forms import *
from .models import *
from userapp.models import *


# Wordhunt Prelims Section A
def question_prelims_sectionA(request):
    #Get the actual start and end date and time of the event
    date_obj=get_object_or_404(test_timings,event="wordhunt",round_type="preliminary")
    start=date_obj.start
    end=date_obj.end
    #Get the current date and time
    current=datetime.datetime.now()
    
    #Compare current with actual start and end date and time
    if start>current:
        return render(request,'show_test.html',{'start':start,'end':end,'status':'before'})
    elif start<=current and current<=end:
        current_user_obj=get_object_or_404(prelim_test,Student=request.user,event='wordhunt')
        if current_user_obj.test_status=="not_started":
            prelim_test.objects.filter(Student=request.user,event='wordhunt').update(start=datetime.datetime.now(),test_status='started',attended=True)
        elif current_user_obj.test_status=='cheated':
            return render(request,'show_test.html',{'status':'cheated'})

        answer_form = Student_Answer(request.POST or None)

        section = True

        page_no = request.GET.get('page', 1)
        question_set = Wordhunt.objects.filter(
            roundtype="prelims", section="A").order_by('id')
        pages = Paginator(question_set, 1)
        try:
           page = pages.page(page_no)
        except EmptyPage:
            page = pages.page(pages.num_pages)
        except PageNotAnInteger:
            page = pages.page(1)

        context = {
            'answer_form': answer_form, 'section': section, 'page': page, 'pages': pages}

        return render(request, 'wordhunt/questionA.html', context=context)

    elif end<current:
        #test = after indicates test has completed already
        return render(request,'show_test.html',{'start':start,'end':end,'status':'after'})
    
    else:
        return HttpResponse("something wrong sorry for the inconvenience")


# Wordhunt Prelims Section A
def question_prelims_sectionB(request):
    #Get the actual start and end date and time of the event
    date_obj=get_object_or_404(test_timings,event="wordhunt",round_type="preliminary")
    start=date_obj.start
    end=date_obj.end

    #Get the current datetime
    current=datetime.datetime.now()

    #Compare current with actual start and end date and time
    if start>current:
        return render(request,'show_test.html',{'start':start,'end':end,'status':'before'})

    elif start<=current and current<=end:
        #Get the current user object
        current_user_obj=get_object_or_404(prelim_test,Student=request.user,event='wordhunt')
        if current_user_obj.test_status=='not_started':
            prelim_test.objects.filter(Student=request.user,event='wordhunt').update(start=datetime.datetime.now(),test_status='started',attended=True)
        elif current_user_obj.test_status=='cheated':
            return render(request,'show_test.html',{'status':'cheated'})
        
        answer_form = Student_Answer(request.POST or None)

        section = True

        page_no = request.GET.get('page', 1)
        question_set = Wordhunt.objects.filter(
          roundtype="prelims", section="B").order_by('id')
        pages = Paginator(question_set, 1)

        try:
           page = pages.page(page_no)
        except EmptyPage:
           page = pages.page(pages.num_pages)
        except PageNotAnInteger:
           page = pages.page(1)

        context = {
            'answer_form': answer_form, 'section': section, 'page': page, 'pages': pages
        }

        return render(request, 'wordhunt/questionB.html', context=context)
        
    elif end<current:
        #test = after indicates test has completed already
        return render(request,'show_test.html',{'start':start,'end':end,'status':'after'})
    
    else:
        return HttpResponse("something wrong sorry for the inconvenience")

# Wordhunt Prelims Section A
def question_finals_sectionA(request):
    #Get the actual start and end date and time of the event
    date_obj=get_object_or_404(test_timings,event="wordhunt",round_type="final")
    start=date_obj.start
    end=date_obj.end
    
    #Get the current date and time
    current=datetime.datetime.now()

    #Compare current with actual start and end date and time
    if start>current:
        return render(request,'show_test.html',{'start':start,'end':end,'status':'before'})

    elif start<=current and current<=end:
        #Some other filtering
        current_user_obj=get_object_or_404(final_test,student=request.user,event='wordhunt')
        if current_user_obj.test_status=="not_started":
            final_test.objects.filter(student=request.user,event='wordhunt').update(start=datetime.datetime.now(),test_status='started',attended=True)
        elif current_user_obj.test_status=="cheated":
            return render(request,'show_test.html',{'status':'cheated'})    
        answer_form = Student_Answer(request.POST or None)

        section = False

        page_no = request.GET.get('page', 1)
        question_set = Wordhunt.objects.filter(
            roundtype="final", section="A").order_by('id')
        pages = Paginator(question_set, 1)
        try:
            page = pages.page(page_no)
        except EmptyPage:
            page = pages.page(pages.num_pages)
        except PageNotAnInteger:
            page = pages.page(1)

        context = {
            'answer_form': answer_form, 'section': section, 'page': page, 'pages': pages}

        return render(request, 'wordhunt/questionA.html', context=context)
    
    elif end<current:
        #test = after indicates test has completed already
        return render(request,'show_test.html',{'start':start,'end':end,'status':'after'})
    
    else:
        return HttpResponse("something wrong sorry for the inconvenience")

# Wordhunt Prelims Section A
def question_finals_sectionB(request):
    #Get the actual start and end date and time of the event
    date_obj=get_object_or_404(test_timings,event="wordhunt",round_type="final")
    start=date_obj.start
    end=date_obj.end

    #Get the current date and time
    current=datetime.datetime.now()

    #Compare current with actual start and end date and time
    if start>current:
        return render(request,'show_test.html',{'start':start,'end':end,'status':'before'}) 
    
    elif start<=current and current<=end:
        #Some other filtering
        current_user_obj=get_object_or_404(final_test,student=request.user,event='wordhunt')
        if current_user_obj.test_status=="not_started":
            final_test.objects.filter(student=request.user,event='wordhunt').update(start=datetime.datetime.now(),test_status='started',attended=True)
        elif current_user_obj.test_status=="cheated":
            return render(request,'show_test.html',{'status':'cheated'})   
        
        answer_form = Student_Answer(request.POST or None)

        section = False

        page_no = request.GET.get('page', 1)
        question_set = Wordhunt.objects.filter(
           roundtype="final", section="B").order_by('id')
        pages = Paginator(question_set, 1)
        try:
            page = pages.page(page_no)
        except EmptyPage:
            page = pages.page(pages.num_pages)
        except PageNotAnInteger:
            page = pages.page(1)

        context = {
            'answer_form': answer_form, 'section': section, 'page': page, 'pages': pages}

        return render(request, 'wordhunt/questionB.html', context=context)
    elif end<current:
        #test = after indicates test has completed already
        return render(request,'show_test.html',{'start':start,'end':end,'status':'after'})
    else:
        return HttpResponse("something wrong sorry for the inconvenience")

# All Prelims & Finals Answer will come here
def answer_submit(request):
    #Get the round of the test :
    round=request.POST.get('round','something wrong')
    if round=='prelims':
        date_obj=get_object_or_404(test_timings,event="wordhunt",round_type="preliminary")
        current_user_obj=get_object_or_404(prelim_test,Student=request.user,event='wordhunt')
    elif round=='finals':
        date_obj=get_object_or_404(test_timings,event="wordhunt",round_type="final")
        current_user_obj=get_object_or_404(final_test,student=request.user,event='wordhunt')
        
    #Get the actual start and end date and time of the event
    start=date_obj.start
    end=date_obj.end
    
    attended = False
    status = False
    failure=True #indicates data is saved within the time or not
    student = request.user
    question_id = request.POST.get('question_id', None)
    question_obj = get_object_or_404(Wordhunt, id=question_id)
    actual_answer = (request.POST.get('answer', None)).lower()
    value = ((request.POST.get('answer', None)).lower()).replace(" ", "")

    if question_obj.correct_answer.lower() == value:
        #print(value, question_id, question_obj.correct_answer)
        status = True

    if Stud_Res_WordHunt.objects.filter(student=student, question=question_obj).exists():
        attended = True
        messages.info(request, "You have already attended this question")
    else:
        #Answer entry is here
        current_time_during_submit=datetime.datetime.now()
        if start<=current_time_during_submit and current_time_during_submit<=end:
            #Checking for cheated
            if current_user_obj.test_status=='cheated':
                return JsonResponse({'status':'cheated'})
            else:    
                student_final_answer = Stud_Res_WordHunt.objects.create(

csevent/templates/wordhunt/final_score.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Word Hunt Score Page | Finals</title>
{% endblock %}

{% block head %}

<style>
    .table_wrapper {
        max-height: 450px;
        overflow-y: auto;
        display: inline-block;
    }

    /* Table */
    /* Table Scrollbar Hide */
    .table::-webkit-scrollbar {
        /* Chrome,Edge,Opera,Firefox */
        width: 0px;
        background: transparent;
    }

    .table_wrapper {
        /* Chrome,Edge,Opera,Firefox */
        scrollbar-width: none;
        -ms-overflow-style: none;
    }

    .table_wrapper::-webkit-scrollbar {
        /* Chrome,Edge,Opera,Firefox */
        width: 0px;
    }
</style>

{% endblock %}

{% block content %}
<h3>Word Hunt Finals</h3>

<section class="container">
    <div class="table-responsive table_wrapper">
        <table class="table my-1 my-md-2">
            <thead>
                <tr class="text-center">
                    <th scope="col">#</th>
                    <th scope="col">Student Email id</th>
                    <th scope="col">Score (20)</th>
                </tr>
            </thead>
            <tbody>
                {% for final in code_score %}
                <tr scope="row" class="text-center">
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{final.student}}</td>
                    <td>{{final.score}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

{% endblock %}

csevent/templates/wordhunt/prelims_score.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Word Hunt Score Page | Prelims</title>
{% endblock %}

{% block head %}

<style>
    .table_wrapper {
        max-height: 450px;
        overflow-y: auto;
        display: inline-block;
    }

    /* Table */
    /* Table Scrollbar Hide */
    .table::-webkit-scrollbar {
        /* Chrome,Edge,Opera,Firefox */
        width: 0px;
        background: transparent;
    }

    .table_wrapper {
        /* Chrome,Edge,Opera,Firefox */
        scrollbar-width: none;
        -ms-overflow-style: none;
    }

    .table_wrapper::-webkit-scrollbar {
        /* Chrome,Edge,Opera,Firefox */
        width: 0px;
    }
</style>

{% endblock %}

{% block content %}
<h3>Word Hunt Prelims</h3>

<section class="container">
    <div class="table-responsive table_wrapper">
        <table class="table my-1 my-md-2">
            <thead>
                <tr class="text-center">
                    <th scope="col">#</th>
                    <th scope="col">Student Email id</th>
                    <th scope="col">Score (20)</th>
                </tr>
            </thead>
            <tbody>
                {% for final in code_score %}
                <tr scope="row" class="text-center">
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{final.student}}</td>
                    <td>{{final.score}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

{% endblock %}

csevent/templates/wordhunt/questionA.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
{% if section %}
<title> Ransack | Round Prelims</title>
{% else %}
<title> Ransack | Round Finals</title>
{% endif %}
{% endblock %}

{% block content %}
<!-- Section A -->
{% if page.object_list %}
<h2>Section A</h2>

{% for question in page.object_list %}

{% for q in question.images.all %}
<img src="{{ q.image.url }}" alt="img" width="250" />
{% endfor %}

<form method="POST" data-id="{{question.id}}">
    {% csrf_token %}
    {{ answer_form|crispy }}
    <!--If you don't put type attribute it will take it as submit type by default and refreshes the form-->
    <button type="button" class="btn btn-success float-right submit_button"
        data-question="{{question.id}}">Submit</button>
    {% if page.has_next %}
        <a href="?page={{page.next_page_number}}" class="btn btn-primary float-right next"
            style="pointer-events:none ; cursor:default">Next</a>
    {% else %}
        {% if section %}
            <a href="{% url 'wordhunt:prelimsB' %}"
                class="btn btn-disabled text-white bg-pink-500 hover:bg-pink-600 focus:ring-4 focus:ring-indigo-300 px-4 m-2  float-right next"
                style="pointer-events:none ; cursor:default">Next</a>
        {% else %}
            <a href="{% url 'wordhunt:finalsB' %}"
                class="btn btn-disabled text-white bg-pink-500 hover:bg-pink-600 focus:ring-4 focus:ring-indigo-300 px-4 m-2  float-right next"
                style="pointer-events:none ; cursor:default">Next</a>
        {% endif %}
    {% endif %}
</form>

{% endfor %}
<h2>{{page}}</h2>
{% else %}
<h1> There might be some problem </h1>
{% endif %}


{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {

        var count = 0, round;
        {% if section %}
        // Prelims
        round = "prelims";
        {% else %}
        // Finals
        round = "finals";
        {% endif %}

        $(window).focus(function () {
            count = count + 1
            if (count === 1) {
                alert("Tab Switching is not Allowed more than 2 times.\nTab Switch Count: 1");
            }
            else if (count === 2) {
                alert("Tab Switching is not Allowed more than 2 times.\nTab Switch Count: 2");
            }
            else {
                alert("Malpractice");
                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'wordhunt:exit_test' %}",
                    type: 'post',
                    data: { 'round': round },
                    dataType: 'json',
                    success: function (data) {
                        if (data.is_taken) {
                            location.reload();
                        }
                    }
                });
            }
        });

        $(".submit_button").click(function () {
            // Answer 
            var answer = $(this).parent().find("#id_user_answer").val();
            // Question id
            var question_id = $(this).attr('data-question');
            if (answer.length == 0) {
                alert("Please fill the answer otherwise you can't go to the next page")
            }
            else {

                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'wordhunt:answer_submit_prelims' %}",
                    type: 'post',
                    data: { 'answer': answer, 'question_id': question_id ,'round':round},
                    dataType: 'json',
                    success: function (data) {
                        if (data['is_taken']) {
                            alert("already submitted");
                            $(".next").removeAttr("style");
                        }
                        else if(data['failure']){
                            alert('Time is over')
                            $(".next").removeAttr("style")
                        }
                        else if(data['status']=='cheated')
                        {
                            alert('Malpractice has been detected for you')
                            $(".next").removeAttr("style")
                        }
                        else {
                            alert("Submitted successfully");
                            $(".next").removeAttr("style");
                        }
                    }
                });
            }
        });
    });
</script>

{% endblock %}

csevent/templates/wordhunt/questionB.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
{% if section %}
<title> Ransack | Round Prelims</title>
{% else %}
<title> Ransack | Round Finals</title>
{% endif %}
{% endblock %}

{% block content %}

{% if page.object_list %}
<h2>Section B</h2>

{% for question in page.object_list %}

{% for q in question.images.all %}
<img src="{{ q.image.url }}" alt="img" width="250" />
{% endfor %}

<form method="POST" data-id="{{question.id}}">
    {% csrf_token %}
    {{ answer_form|crispy }}
    <button type="button" class="btn btn-success float-right submit_button"
        data-question="{{question.id}}">Submit</button>
    {% if page.has_next %}
    <a href="?page={{page.next_page_number}}" class="btn btn-primary float-right next"
        style="pointer-events: none;cursor:default;">Next</a>
    {% else %}
        {% if section %}
            <a href="{% url 'wordhunt:finished_test' 1 %}" class="btn btn-primary float-right next"
                style="pointer-events:none;cursor:default">Next</a>
        {% else %}
            <a href="{% url 'wordhunt:finished_test' 2 %}" class="btn btn-primary float-right next"
                style="pointer-events:none;cursor:default">Next</a>
        {% endif %}
    {% endif %}
</form>

{% endfor %}
<h2>{{page}}</h2>
{% else %}
<h1> There might be some problem </h1>
{% endif %}

{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {

        var count = 0, round;
        {% if section %}
        // Prelims
        round = "prelims";
        {% else %}
        // Finals
        round = "finals";
        {% endif %}

        $(window).focus(function () {
            count = count + 1
            if (count === 1) {
                alert("Tab Switching is not Allowed more than 2 times.\nTab Switch Count: 1");
            }
            else if (count === 2) {
                alert("Tab Switching is not Allowed more than 2 times.\nTab Switch Count: 2");
            }
            else {
                alert("Malpractice");
                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'wordhunt:exit_test' %}",
                    type: 'post',
                    data: { 'round': round },
                    dataType: 'json',
                    success: function (data) {
                        if (data.is_taken) {
                            location.reload();
                        }
                    }
                });
            }
        });

        $(".submit_button").click(function () {
            // Answer 
            var answer = $(this).parent().find("#id_user_answer").val();
            // Question id
            var question_id = $(this).attr('data-question');
            if (answer.length == 0) {
                alert("Please fill the answer otherwise you can't go to the next page")
            }
            else {

                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'wordhunt:answer_submit_prelims' %}",
                    type: 'post',
                    data: { 'answer': answer, 'question_id': question_id,'round':round },
                    dataType: 'json',
                    success: function (data) {
                        if (data['is_taken']) {
                            alert("already entered")
                            $('.next').removeAttr("style")
                        }
                        else if(data['failure']){
                            alert('Time is over')
                            $('.next').removeAttr("style")
                        }
                        else if(data['status']=='cheated')
                        {
                            alert('Malpractice has been detected for you')
                            $(".next").removeAttr("style")
                        }
                        else {
                            alert("Submitted successfully");
                            $('.next').removeAttr("style")
                        }
                      
                    }
                });
            }
        });
    });
</script>

{% endblock %}