csevent/csevent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .views import *


urlpatterns = [
    path('verification/', include('verify_email.urls'), name='verification'),
    path('admin/', admin.site.urls),
    path('', homepage, name="homepage"),
    path('accounts/', include('userapp.urls')),
    path('events/codetreasure/', include('codetreasure.urls')),
    path('events/ransack/', include('wordhunt.urls')),
    path('events/', include('imageupload.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

csevent/imageupload/urls.py
from django.urls import path
from .views import *


app_name = "imageupload"

urlpatterns = [
    # Test Web Dodger Prelims
    path('webdodger/prelims/', poster_prelims, name='poster_prelims'),
    path('webdodger/finals/', poster_finals, name='poster_finals'),
    # Test Impreza Prelims
    path('impreza/prelims/', logo_prelims, name='logo_prelims'),
    path('impreza/finals/', logo_finals, name='logo_finals'),
    # Finished Status
    path('success/', success, name='success'),
    path('verify/metadata/', verify_meta_img, name="verify_meta"),
    # Logo Score
    path('impreza/prelims/result/score/', display_logo_prelims,
         name='display_logo_prelims'),
    path('impreza/finals/result/score/', display_logo_finals,
         name='display_logo_finals'),
    # Poster Score  
    # Display Logo & Poster
    path('webdodger/prelims/result/score/', display_poster_prelims,
         name='display_poster_prelims'),
    path('webdodger/finals/result/score/', display_poster_finals,
         name='display_poster_finals'),
]

csevent/questions/urls.py
from django.urls import path
from .views import *

app_name='codetreasure'

#Define your urls here

urlpatterns=[
    path('prelims/',prelm_question,name='prelims'),
    path('final_code_shuffle/',final_code_shuffle_function,name='final_code_shuffle_function'),
    path('final_binary/',final_binary_function,name='final_binary_function'),
    path('last_binary_question/',last_binary_question,name='last_binary_question'),
    path('final_spot_error/',final_spot_error_function,name='final_spot_error_function'),
]

csevent/userapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *
app_name='user_app'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    # SignUp Form
    path('registration/', signup, name="signup"),
    # Myaccount (Edit)
    path('myaccount/', myaccount, name="myaccount"),
    # Events Register
    path('event_register/', event_register, name="event_register"),
    # 4 Events only 1 offline-mail
    path('event_register/ransack/', register_ransack, name="register_ransack"),
    path('event_register/codetreasure/', register_codetreasure,
         name="register_codetreasure"),
    path('event_register/impreza/', register_impreza, name="register_impreza"),
    path('event_register/webdodger/',
         register_webdodger, name="register_webdodger"),


    # Dummy for Demo
    path('demo/', demo_link, name="demo"),

]

csevent/wordhunt/urls.py
from django.urls import path
from .views import *

app_name = "wordhunt"

urlpatterns = [
    # Reteriving Q/A for Prelims & Finals
    path('prelims/sectionA/', question_prelims_sectionA, name="prelims"),
    path('prelims/sectionB/', question_prelims_sectionB, name="prelimsB"),
    path('finals/sectionA/', question_finals_sectionA, name="finals"),
    path('finals/sectionB/', question_finals_sectionB, name="finalsB"),
    # Answer Submission URl for Prelims & Finals
    path('prelims/submit_answer/', answer_submit, name="answer_submit_prelims"),
    # Cheated Prelims & Finals
    path('text/exit/', exit_test, name="exit_test"),
    # Test submitted
    path('finished_test/<int:id>/', finished_test, name="finished_test"),
]

csevent/userapp/forms.py
from django import forms

from .models import *


class UserForm(forms.ModelForm):
    mobile = forms.CharField(widget=forms.NumberInput(
        attrs={'placeholder': 'Enter your Mobile Number'}), label="Mobile Number :")
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Password', }), label="Password :")
    confirm_password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Confirm Password'}), label="Confirm Password :")

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'mobile',
                  'email', 'password', 'confirm_password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update(
            {'placeholder': 'Enter your First name', 'class': 'input_cust capitalize'})
        self.fields['last_name'].widget.attrs.update(
            {'placeholder': 'Enter your Last name', 'class': 'input_cust capitalize'})
        self.fields['email'].widget.attrs.update(
            {'placeholder': 'eg..abc@example.com', 'class': 'input_cust'})

        self.fields['email'].label = "Email Address :"
        self.fields['last_name'].label = "Last Name :"
        self.fields['first_name'].label = "First Name :"

    def clean_email(self):
        email = self.cleaned_data.get('email').lower()
        return email

    def clean_confirm_password(self):
        c_pass = self.cleaned_data.get('confirm_password')
        if not c_pass == self.cleaned_data.get('password'):
            raise forms.ValidationError('Password did not match')
        return c_pass

    # validating the mobile no
    def clean_mobile(self):
        mobile = self.cleaned_data.get('mobile')
        if not len(mobile) == 10:
            raise forms.ValidationError('Enter a valid Mobile Number')
        if not mobile.isnumeric():
            raise forms.ValidationError('Mobile Number must be a Integer')
        return mobile


class StudentForm(forms.ModelForm):

    class Meta:
        model = StudentModel
        fields = ['college', 'dept',
                  'roll_no', 'id_proof', 'profile_pic', 'bonafide', 'college_address', 'address']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['college_address'].widget.attrs.update(
            {'placeholder': 'Full address of your college', 'rows': '5'})
        self.fields['address'].widget.attrs.update(
            {'placeholder': 'Enter your residential address', 'rows': '5'})

        self.fields['college'].label = "Name of the College :"
        self.fields['dept'].label = "Department :"
        self.fields['roll_no'].label = "Roll Number :"
        self.fields['id_proof'].label = "Identity Card :"
        self.fields['profile_pic'].label = "Participant Photo :"
        self.fields['college_address'].label = "College Address :"
        self.fields['address'].label = "Address :"
        self.fields['bonafide'].label = "Bonafide :"
        self.fields['bonafide'].required = False


# Myaccount
class User_Form(forms.ModelForm):
    mobile = forms.CharField(widget=forms.NumberInput(
        attrs={'placeholder': 'Enter your Mobile Number'}), label="Mobile Number :")

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'mobile']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update(
            {'placeholder': 'Enter your First name'})
        self.fields['last_name'].widget.attrs.update(
            {'placeholder': 'Enter your Last name'})

        self.fields['last_name'].label = "Last Name :"
        self.fields['first_name'].label = "First Name :"

    def clean_confirm_password(self):
        c_pass = self.cleaned_data.get('confirm_password')
        if not c_pass == self.cleaned_data.get('password'):
            raise forms.ValidationError('Password did not match')
        return c_pass

    # validating the mobile no
    def clean_mobile(self):
        mobile = self.cleaned_data.get('mobile')
        if not len(mobile) == 10:
            raise forms.ValidationError('Enter a valid Mobile Number')
        if not mobile.isnumeric():
            raise forms.ValidationError('Mobile Number must be a Integer')
        return mobile

csevent/userapp/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from verify_email.email_handler import send_verification_email

from .decorators import *
from .models import *
from .forms import *


def signup(request):
    form = UserForm(request.POST or None)
    form1 = StudentForm(request.POST or None, request.FILES or None)

    if form.is_valid() and form1.is_valid():
        form_obj = send_verification_email(request, form)
        print(form_obj)
        """form_obj = form.save(commit=False)
        form_obj.user_type = 3
        form_obj.save()"""
        # Student Form
        from1_obj = form1.save(commit=False)
        from1_obj.user = User.objects.get(id=form_obj.id)
        from1_obj.save()

        return redirect('homepage')

    content = {
        'form': form, 'form1': form1
    }

    return render(request, 'userapp/registration.html', context=content)


def myaccount(request):
    form = User_Form(request.POST or None, instance=request.user)
    form1 = StudentForm(request.POST or None,
                        request.FILES or None, instance=request.user.student)

    if request.method == "POST":
        if form.is_valid() and form1.is_valid():
            form.save()
            form1.save()
            messages.success(
                request, "Your Account details saved successfully")
            return redirect("myaccount", permanent=True)

    content = {
        'form': form, 'form1': form1
    }

    return render(request, 'userapp/myaccount.html', context=content)


# Registration Page
def event_register(request):
    return render(request, "userapp/event_register.html")

@is_student
def register_codetreasure(request):
    # registering this event
    StudentModel.objects.filter(user=request.user).update(is_codetreasure=True)
    # registering event for test
    if not prelim_test.objects.filter(Student=request.user, event='codetreasure').exists():
        prelim_test.objects.create(Student=request.user,
                                   event='codetreasure', test_status='not_started')
        messages.info(request, "Successfully registered for Code Treasure")
    return render(request, "userapp/event_register.html")

@is_student
def register_impreza(request):
    # registering this event
    StudentModel.objects.filter(user=request.user).update(is_impreza=True)
    # registering event for test
    if not prelim_test.objects.filter(Student=request.user, event='logo').exists():
        prelim_test.objects.create(Student=request.user,
                                   event='logo', test_status='not_started')
        messages.info(request, "Successfully registered for Impreza")
    return render(request, "userapp/event_register.html")

@is_student
def register_webdodger(request):
    # registering this event
    StudentModel.objects.filter(user=request.user).update(is_webdodger=True)
    # registering event for test
    if not prelim_test.objects.filter(Student=request.user, event='poster').exists():
        prelim_test.objects.create(Student=request.user,
                                   event='poster', test_status='not_started')
        messages.info(request, "Successfully registered for Web Dodger")
    return render(request, "userapp/event_register.html")

@is_student
def register_ransack(request):
    # registering this event
    StudentModel.objects.filter(user=request.user).update(is_ransack=True)
    # registering event for test
    if not prelim_test.objects.filter(Student=request.user, event='wordhunt').exists():
        prelim_test.objects.create(Student=request.user,
                                   event='wordhunt', test_status='not_started')
    return render(request, "userapp/event_register.html")

@is_student
def register_geekspeak(request):
    # registering this event
    StudentModel.objects.filter(user=request.user).update(is_geekspeak=True)
    # registering event for test
    if not final_test.objects.filter(student=request.user, event='ppt').exists():
        final_test.objects.create(student=request.user,
                                  event='ppt', test_status='not_started', placed="notselected")
        messages.info(request, "Successfully registered for GeekSpeak")
    return render(request, "userapp/event_register.html")

csevent/templates/userapp/event_test.html
{% extends 'base.html' %}
{% block content %}
<h2>All Prelims</h2>
<br>
<a class="btn btn-primary" href="{% url 'wordhunt:prelims' %}" role="button">ransack Test</a>
<a class="btn btn-primary" href="{% url 'codetreasure:prelims' %}" role="button">codetreasure Test</a>
<a class="btn btn-primary" href="{% url 'imageupload:logo_prelims' %}" role="button">impreza Test</a>
<a class="btn btn-primary" href="{% url 'imageupload:poster_prelims' %}" role="button">webdodger Test</a>
<br>
<br>
<h2>All Finals</h2>
<br>
<a class="btn btn-primary" href="{% url 'wordhunt:finals' %}" role="button">ransack Test</a>
<a class="btn btn-primary" href="{% url 'codetreasure:final_code_shuffle_function' %}" role="button">codetreasure
    Test</a>
<a class="btn btn-primary" href="{% url 'imageupload:logo_finals' %}" role="button">impreza Test</a>
<a class="btn btn-primary" href="{% url 'imageupload:poster_finals' %}" role="button">webdodger Test</a>
{% endblock %}

csevent/templates/userapp/myaccount.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container-fluid bg-gradient-to-r from-indigo-400 to-purple-600">
    <form method="POST" class="form needs-validation" enctype="multipart/form-data" autocomplete="off" novalidate>
        {% csrf_token %}
        <div class="text-center">
            <h2 class="m-0 text-white">Student Registration Form</h2>
        </div>
        <div class="grid grid-cols-1 col-6 mx-auto my-4 gap-10">
            <div class="rounded-3xl shadow p-4 bg-white text-indigo-500">
                <h3 class="text-center">Personal Details</h3>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        {{ form1.profile_pic|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 pr-md-2">
                        {{ form.first_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 pl-md-2">
                        {{ form.last_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 pl-md-2">
                        {{ form.mobile|as_crispy_field }}
                    </div>
                    <div class="form-group col-12 pr-md-2">
                        {{ form1.address|as_crispy_field }}
                    </div>
                </div>
                <h3 class="text-center">Student Details</h3>
                <div class="form-row">
                    <div class="form-group col-md-6 pr-md-2">
                        {{ form1.college|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 pl-md-2">
                        {{ form1.college_address|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 pr-md-2">
                        {{ form1.dept|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 pl-md-2">
                        {{ form1.roll_no|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 pr-md-2">
                        {{ form1.id_proof|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 pr-md-2">
                        {{ form1.bonafide|as_crispy_field }}
                    </div>
                    <div class="form-group col-12 d-flex justify-content-center justify-content-md-start">
                        <button
                            class="btn mx-auto text-white bg-pink-500 hover:bg-pink-600 focus:ring-4 focus:ring-pink-300 px-4 mx-2"
                            type="submit">
                            Save
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

csevent/templates/userapp/register_codetreasure.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="container my-3">
	<div class="col-8 col-lg-4 mx-auto">
		<img class="w-100" src="{% static 'img/code_treasure_logo.png' %}">
	</div>

	<div class="grid grid-cols-1 space-10 rounded-3xl shadow">
		<div class="row p-4">
			<div class="col-12 px-4 py-2">
				<p class="text-lg">Code Treassure is an event which consists of various technical related questions like code shuffling,binary code ,spot the irrelevant line, technical quiz etc.</p><br>
				<div class="">
					<span class="font-semibold">Rounds : </span><span class="text-gray-500">Prelims(12th March, 2021), Finals(13th March, 2021)</span>
				</div>
			</div>
			<div class="col-12 px-4 py-2">
				<div><p class="text-lg font-semibold mb-2">Instructions :</p></div>
				<ul class="px-3 text-indigo-600">
					<li><i class="fas fa-angle-double-right  pr-2"></i>Single participant.</li>
					<li><i class="fas fa-angle-double-right text-indigo-600 pr-2"></i>Prelims consists of technical related 25 aptitude questions (computer Science).</li>
					<li><i class="fas fa-angle-double-right text-indigo-600 pr-2"></i>Time duration for prelims: 20 minutes</li>
					<li><i class="fas fa-angle-double-right text-indigo-600 pr-2"></i>Final will consist of 10 questions.</li>
					<li><i class="fas fa-angle-double-right text-indigo-600 pr-2"></i>Time  duration for Final : 1hour.</li>
					<li><i class="fas fa-angle-double-right text-indigo-600 pr-2"></i>Registered participants only allowed.</li>
					<li><i class="fas fa-angle-double-right text-indigo-600 pr-2"></i>Students should have their college Id card and registration Id before logging in.</li>
					<li><i class="fas fa-angle-double-right text-indigo-600 pr-2"></i>Top 2 Participants will be awarded with winner certificate.</li>
					<li><i class="fas fa-angle-double-right text-indigo-600 pr-2"></i>Certificates will be provided for all the Participants.</li>
				</ul>
			</div>
			<div class="col-12 px-4 py-2">
				<div><p class="text-lg font-semibold mb-2">Do's :</p></div>
				<ul class="list-disc px-3">
					<li class="fas fa-check text-green-400">&nbsp;&nbsp;Answer all the questions</li>
				</ul>
			</div>
			<div class="col-12 px-4 py-2">
				<div><p class="text-lg font-semibold mb-2">Dont's :</p></div>
				<ul class="list-disc px-3">
					<li class="fas fa-times text-red-400">&nbsp;&nbsp;Switching of tabs will not be allowed.</li>
				</ul>
			</div>
			<div class="col-12 px-4 py-2 my-2">
				<form method="POST">
					{% csrf_token %}
					<button type="submit" class="btn text-white bg-pink-500 hover:bg-pink-600 focus:ring-4 focus:ring-pink-300 px-4 mx-2">Register</button>
				</form>
			</div>
		</div>
	</div>
</section>

<a class="btn btn-primary" href="{% url 'register_ransack' %}" role="button">ransack</a>
<a class="btn btn-primary" href="{% url 'register_codetreasure' %}" role="button">codetreasure</a>
<a class="btn btn-primary" href="{% url 'register_impreza' %}" role="button">impreza</a>
<a class="btn btn-primary" href="{% url 'register_webdodger' %}" role="button">webdodger</a>

{% endblock %}

csevent/templates/userapp/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container-fluid bg-gradient-to-r from-indigo-400 to-purple-600">
    <form method="POST" class="form needs-validation" enctype="multipart/form-data" autocomplete="off" novalidate>
        {% csrf_token %}
    <div class="text-center">
        <h2 class="m-0 text-white">Student Registration Form</h2>
    </div>
    <div class="grid grid-cols-1 col-12 col-md-10 col-lg-6 mx-auto my-4 ">
        <div class="rounded-3xl shadow p-4 bg-white text-indigo-500">
            <h3 class="text-center">Personal Details</h3>
            <div class="form-row" id="create_staff">
            <div class="form-group col-md-12">
                {{ form1.profile_pic|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 pr-md-2">
                {{ form.first_name|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 pl-md-2">
                {{ form.last_name|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 pl-md-2">
                {{ form.mobile|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 pr-md-2">
                {{ form.email|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 pr-md-2">
                {{ form.password|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 pl-md-2">
                {{ form.confirm_password|as_crispy_field }}
            </div>
            <div class="form-group col-12 pr-md-2">
                {{ form1.address|as_crispy_field }}
            </div>
            </div>
            <h3 class="text-center">Student Details</h3>
            <div class="form-row" id="">
            <div class="form-group col-md-6 pr-md-2">
                {{ form1.college|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 pl-md-2">
                {{ form1.college_address|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 pr-md-2">
                {{ form1.dept|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 pl-md-2">
                {{ form1.roll_no|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 pr-md-2">
                {{ form1.id_proof|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 pr-md-2">
                {{ form1.bonafide|as_crispy_field }}
            </div>
            <div class="form-group col-12 d-flex justify-content-center justify-content-md-start">
                <button class="btn mx-auto text-white bg-pink-500 hover:bg-pink-600 focus:ring-4 focus:ring-pink-300 px-4 mx-2" type="submit">
                    Register
                </button>
            </div>
        </div>
        </div>
    </div>
    </form>
</div>
{% endblock %}