csevent/csevent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .views import *


urlpatterns = [
    path('verification/', include('verify_email.urls'), name='verification'),
    path('admin/', admin.site.urls),
    path('', homepage, name="homepage"),
    path('accounts/', include('userapp.urls')),
    path('events/codetreasure/', include('codetreasure.urls')),
    path('events/ransack/', include('wordhunt.urls')),
    path('events/', include('imageupload.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

csevent/imageupload/urls.py
from django.urls import path
from .views import *


app_name = "imageupload"

urlpatterns = [
    # Test Web Dodger Prelims
    path('webdodger/prelims/', poster_prelims, name='poster_prelims'),
    path('webdodger/finals/', poster_finals, name='poster_finals'),
    # Test Impreza Prelims
    path('impreza/prelims/', logo_prelims, name='logo_prelims'),
    path('impreza/finals/', logo_finals, name='logo_finals'),
    # Finished Status
    path('success/', success, name='success'),
    path('verify/metadata/', verify_meta_img, name="verify_meta"),
    # Logo Score
    path('impreza/prelims/result/score/', display_logo_prelims,
         name='display_logo_prelims'),
    path('impreza/finals/result/score/', display_logo_finals,
         name='display_logo_finals'),
    # Poster Score  
    # Display Logo & Poster
    path('webdodger/prelims/result/score/', display_poster_prelims,
         name='display_poster_prelims'),
    path('webdodger/finals/result/score/', display_poster_finals,
         name='display_poster_finals'),
]

csevent/imageupload/models.py
from django.db import models

from wordhunt.models import User



# Student Result Logo
class Logo(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    logo = models.ImageField(upload_to='Logo')
    score = models.PositiveIntegerField(default=0)
    roundtype_choice = (('prelims', 'Prelims'), ('final', 'Finals'))
    roundtype = models.CharField(
        max_length=8, choices=roundtype_choice)
    description = models.TextField(max_length=430)
    date_time = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Logo Result'

# Student Result Poster both prelims & finals


class Poster(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    poster = models.ImageField(upload_to='Poster')
    status = models.BooleanField()
    score = models.PositiveIntegerField(default=0)
    roundtype_choice = (('prelims', 'Prelims'), ('final', 'Finals'))
    roundtype = models.CharField(
        max_length=8, choices=roundtype_choice)
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Poster Result'

csevent/imageupload/forms.py
from django.forms import ModelForm
from .models import *


class LogoForm(ModelForm):

    class Meta:
        model = Logo
        fields = ['logo', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['description'].widget.attrs.update(
            {'placeholder': 'Describe your logo', 'rows': '5'})
        self.fields['logo'].label = "Upload your Logo"
        self.fields['description'].label = "Description : "
        self.fields['description'].required = False


class LogoFinalForm(ModelForm):

    class Meta:
        model = Logo
        fields = ['logo']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['logo'].label = "Upload your Logo"


class PosterForm(ModelForm):

    class Meta:
        model = Poster
        fields = ['poster']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['poster'].label = "Upload your Poster"


class LogoScoreForm(ModelForm):
    class Meta:
        model = Logo
        fields = ['score']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['score'].widget.attrs.update(
            {'placeholder': 'Score..'})


class PosterScoreForm(ModelForm):
    class Meta:
        model = Poster
        fields = ['score']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['score'].widget.attrs.update(
            {'placeholder': 'Score..'})

csevent/imageupload/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, JsonResponse

from userapp.models import *
from .models import *
from .forms import *
from .image import meta_data

from datetime import datetime

# Poster Prelims
def poster_prelims(request):
    #get the date and time of the logo
    date_obj=get_object_or_404(test_timings,event='poster',round_type='preliminary')
    start=date_obj.start
    end=date_obj.end
    #section=true indicates the prelims round
    section = True
    
    if request.method == 'POST':
        if Poster.objects.filter(student=request.user, roundtype="prelims").exists():
            messages.info(
                request, "You have already uploaded your Documnet")
            return render(request,'success.html')
        else:
            #check for the current time
            current=datetime.now()
            if start>current:
                return render(request,'show_test.html',{'start':start,'end':end,'status':'before'})
            elif start<=current and current<=end:
                form = PosterForm(request.POST or None, request.FILES or None)
                if form.is_valid():
                   obj = form.save(commit=False)
                   obj.student = request.user
                   obj.status = False
                   obj.roundtype = "prelims"
                   obj.save()
                   prelim_test.objects.filter(Student=request.user,event='poster').update(end=current,test_status='finished')
                   messages.success(request,'Saved successfully')
                   return render(request,'success.html')
            elif end<current:
                return render(request,'show_test.html',{'start':start,'end':end,'status':'after'})
            else:
                return HttpResponse('something wrong')
    else:
        current=datetime.now()
        if start>current:
            return render(request,'show_test.html',{'start':start,'end':end,'status':'before'})
            #status = before indicates test still exist
        elif start<=current and current<=end:
            #get the current user object :
            current_user_obj=get_object_or_404(prelim_test,Student=request.user,event='poster')
            if current_user_obj.test_status=="not_started":
                prelim_test.objects.filter(Student=request.user,event='poster').update(start=current,test_status='started',attended=True)
            elif current_user_obj.test_status=="finished":
                messages.warning(request,"You have already posted your logo")
                return render(request,'success.html')
            form = PosterForm()
        elif end<current:
                return render(request,'show_test.html',{'start':start,'end':end,'status':'after'})
        else:
            return HttpResponse('something wrong')
    context = {
        'form': form, 'section': section
    }

    return render(request, 'imageupload/poster.html', context=context)


# Poster Finals
def poster_finals(request):
    form = PosterForm()
    section = False

    if request.method == 'POST':
        if Poster.objects.filter(student=request.user, roundtype="final").exists():
            messages.info(
                request, "You have already uploaded your Documnet")
            return redirect('imageupload:poster_finals')
        else:
            form = PosterForm(request.POST or None, request.FILES or None)
            if form.is_valid():
                obj = form.save(commit=False)
                obj.student = request.user
                obj.status = False
                obj.roundtype = "final"
                obj.save()
                return redirect('imageupload:success')

    context = {
        'form': form, 'section': section
    }

    return render(request, 'imageupload/poster.html', context=context)


# Logo Prelims
def logo_prelims(request):
    #get the date and time of the logo
    date_obj=get_object_or_404(test_timings,event='logo',round_type='preliminary')
    start=date_obj.start
    end=date_obj.end
    
    #section=true indicates the prelims round
    section = True
    if request.method == 'POST':
        if Logo.objects.filter(student=request.user, roundtype="prelims").exists():
            messages.info(
                request, "You have already uploaded your logo")
            return render(request,'success.html')
        else:
            #check for the current time
            current=datetime.now()
            if start>current:
                return render(request,'show_test.html',{'start':start,'end':end,'status':'before'})
            elif start<=current and current<=end:
                form = LogoForm(request.POST, request.FILES)
                if form.is_valid():
                    obj = form.save(commit=False)
                    obj.student = request.user
                    obj.roundtype = "prelims"
                    # meta_data()
                    obj.save()
                    prelim_test.objects.filter(Student=request.user,event='logo').update(end=current,test_status='finished')
                    messages.success(request,'Saved successfully')
                    return render(request,'success.html')
                #If the form is invalid  then it won't save and send the error containing form to the form displayed html page 
            elif end<current:
                return render(request,'show_test.html',{'start':start,'end':end,'status':'after'})
            else:
                return HttpResponse('Something wrong')
    else:
        current=datetime.now()
        if start>current:
            return render(request,'show_test.html',{'start':start,'end':end,'status':'before'})
            #status = True indicates test still exist
        elif start<=current and current<=end:
            #get the current user object :
            current_user_obj=get_object_or_404(prelim_test,Student=request.user,event='logo')
            #Update prelim_test model for the particular user
            if current_user_obj.test_status=="not_started":
                prelim_test.objects.filter(Student=request.user,event='logo').update(start=current,test_status='started',attended=True)
            elif current_user_obj.test_status=="finished":
                messages.warning(request,"You have already posted your logo")
                return render(request,'success.html')
            form = LogoForm()
        elif end<current:
            #test = after indicates test has completed already
            return render(request,'show_test.html',{'start':start,'end':end,'status':'after'})
    context = {
        'form': form, 'section': section
    }
    return render(request, 'imageupload/logo.html', context=context)


# Logo Finals
def logo_finals(request):
    form = LogoFinalForm()
    section = False

    if request.method == 'POST':
        if Logo.objects.filter(student=request.user, roundtype="final").exists():
            messages.info(
                request, "You have already uploaded your Documnet")
            return redirect('imageupload:logo_finals')
        else:
            form = LogoFinalForm(request.POST, request.FILES)
            if form.is_valid():
                obj = form.save(commit=False)
                obj.student = request.user
                obj.status = False
                obj.roundtype = "final"
                # meta_data()
                obj.save()
                return redirect('imageupload:success')

    context = {
        'form': form, 'section': section
    }

    return render(request, 'imageupload/logo.html', context=context)


#  Status
def success(request):
    return HttpResponse('successfully uploaded')


def verify_meta_img(request):
    Result = Poster.objects.all()

    context = {'form': True}

    return render(request, 'imageupload/logo.html', context)


# Cheated Both Logo & Poster -- Finals & Prelims
def exit_test(request):
    messages.warning(request, "Tab Switch Deteched")
    status = True

    if request.method == "POST":
        round1 = request.POST.get('round')
        events = request.POST.get('event')
        if round1 == "prelims":
            prelim_test.objects.filter(
                Student=request.user, event=events).update(test_status="cheated")
        elif round1 == "finals":
            final_test.objects.filter(
                student=request.user, event=events).update(test_status="cheated")

    data = {
        'is_taken': status
    }
    return JsonResponse(data)


# Score Board for Logo Prelims
def display_logo_prelims(request):
    # getting all the objects of Logo .
    score = LogoScoreForm(request.POST or None)
    logo = Logo.objects.filter(roundtype="prelims").order_by('id')

    if request.method == "POST":
        question_id = get_object_or_404(Logo, id=request.POST.get('q_id'))
        Logo.objects.filter(id=question_id.id).update(
            score=request.POST.get('answer'))

        return JsonResponse({'result': 'Good'})

    context = {'logo': logo, 'score': score}

    return render(request, 'imageupload/display_logo.html', context=context)


# Score Board for Logo Finals
def display_logo_finals(request):
    # getting all the objects of Logo .
    score = LogoScoreForm(request.POST or None)
    logo = Logo.objects.filter(roundtype="final").order_by('id')

    if request.method == "POST":
        question_id = get_object_or_404(Logo, id=request.POST.get('q_id'))
        Logo.objects.filter(id=question_id.id).update(
            score=request.POST.get('answer'))

        return JsonResponse({'result': 'Good'})

    context = {'logo': logo, 'score': score}

    return render(request, 'imageupload/display_logo_finals.html', context=context)


# Score Board for Poster Prelims
def display_poster_prelims(request):
    # getting all the objects of Poster .
    score = PosterScoreForm(request.POST or None)
    poster = Poster.objects.filter(roundtype="prelims").order_by('id')

csevent/templates/imageupload/display_logo.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Logo Score Page | Prelims</title>
{% endblock %}

{% block head %}

<style>
    .table_wrapper {
        max-height: 450px;
        overflow-y: auto;
        display: inline-block;
    }

    /* Table */
    /* Table Scrollbar Hide */
    .table::-webkit-scrollbar {
        /* Chrome,Edge,Opera,Firefox */
        width: 0px;
        background: transparent;
    }

    .table_wrapper {
        /* Chrome,Edge,Opera,Firefox */
        scrollbar-width: none;
        -ms-overflow-style: none;
    }

    .table_wrapper::-webkit-scrollbar {
        /* Chrome,Edge,Opera,Firefox */
        width: 0px;
    }
</style>

{% endblock %}

{% block content %}
<h3>Logo Prelims</h3>
<section class="container my-5">
    <div class="table-responsive table_wrapper">
        <table class="table my-1 my-md-2">
            <thead>
                <tr class="text-center">
                    <th scope="col">#</th>
                    <th scope="col">Logo</th>
                    <th scope="col">Student Email id</th>
                    <th scope="col">Description</th>
                    <th scope="col">Uploaded</th>
                    <th scope="col">Score</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for logo in logo %}
                <tr scope="row" class="text-center">
                    <th scope="row">{{forloop.counter}}</th>
                    <td>
                        <a href="{{logo.logo.url}}" class="text-primary" target="_blank"
                            rel="noopener noreferrer">{{logo.logo}}</a>
                    </td>
                    <td>{{logo.student}}</td>
                    <td>{{logo.description}}</td>
                    <td>{{logo.date_time}}</td>
                    <td>
                        <input type="text" class="form-control" placeholder="Score..." value="{{logo.score}}">
                    </td>
                    <td>
                        <button class="btn btn-success float-left submit_button"
                            data-question="{{logo.id}}">Save</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

{% endblock %}


{% block script %}
<script>
    $(document).ready(function () {

        $(".submit_button").click(function () {
            //Question id
            var q_id = $(this).attr('data-question');
            //answer
            var answer = $(this).parent().prev().children().val();
            if (answer.length == 0) {
                alert("Please fill the answer otherwise you can't go to the next page")
            }
            else {
                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'imageupload:display_logo_prelims' %}",
                    type: 'post',
                    data: { 'answer': answer, 'q_id': q_id },
                    dataType: 'json',
                    success: function (data) {
                        if (data['result'] == "Good") {
                            alert("Saved")
                        }
                    }
                });
            }

        });
    });
</script>
{% endblock %}

csevent/templates/imageupload/display_logo_finals.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Logo Score Page | Finals</title>
{% endblock %}

{% block head %}

<style>
    .table_wrapper {
        max-height: 450px;
        overflow-y: auto;
        display: inline-block;
    }

    /* Table */
    /* Table Scrollbar Hide */
    .table::-webkit-scrollbar {
        /* Chrome,Edge,Opera,Firefox */
        width: 0px;
        background: transparent;
    }

    .table_wrapper {
        /* Chrome,Edge,Opera,Firefox */
        scrollbar-width: none;
        -ms-overflow-style: none;
    }

    .table_wrapper::-webkit-scrollbar {
        /* Chrome,Edge,Opera,Firefox */
        width: 0px;
    }
</style>

{% endblock %}

{% block content %}
<h3>Logo Finals</h3>
<section class="container my-5">
    <div class="table-responsive table_wrapper">
        <table class="table my-1 my-md-2">
            <thead>
                <tr class="text-center">
                    <th scope="col">#</th>
                    <th scope="col">Logo</th>
                    <th scope="col">Student Email id</th>
                    <th scope="col">Uploaded</th>
                    <th scope="col">Score</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for logo in logo %}
                <tr scope="row" class="text-center">
                    <th scope="row">{{forloop.counter}}</th>
                    <td>
                        <a href="{{logo.logo.url}}" class="text-primary" target="_blank"
                            rel="noopener noreferrer">{{logo.logo}}</a>
                    </td>
                    <td>{{logo.student}}</td>
                    <td>{{logo.date_time}}</td>
                    <td>
                        <input type="text" class="form-control" placeholder="Score..." value="{{logo.score}}">
                    </td>
                    <td>
                        <button class="btn btn-success float-left submit_button"
                            data-question="{{logo.id}}">Save</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

{% endblock %}


{% block script %}
<script>
    $(document).ready(function () {

        $(".submit_button").click(function () {
            //Question id
            var q_id = $(this).attr('data-question');
            //answer
            var answer = $(this).parent().prev().children().val();
            if (answer.length == 0) {
                alert("Please fill the answer otherwise you can't go to the next page")
            }
            else {
                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'imageupload:display_logo_finals' %}",
                    type: 'post',
                    data: { 'answer': answer, 'q_id': q_id },
                    dataType: 'json',
                    success: function (data) {
                        if (data['result'] == "Good") {
                            alert("Saved")
                        }
                    }
                });
            }

        });
    });
</script>
{% endblock %}

csevent/templates/imageupload/display_poster_finals.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Poster Score Page | Finals</title>
{% endblock %}

{% block head %}

<style>
    .table_wrapper {
        max-height: 450px;
        overflow-y: auto;
        display: inline-block;
    }

    /* Table */
    /* Table Scrollbar Hide */
    .table::-webkit-scrollbar {
        /* Chrome,Edge,Opera,Firefox */
        width: 0px;
        background: transparent;
    }

    .table_wrapper {
        /* Chrome,Edge,Opera,Firefox */
        scrollbar-width: none;
        -ms-overflow-style: none;
    }

    .table_wrapper::-webkit-scrollbar {
        /* Chrome,Edge,Opera,Firefox */
        width: 0px;
    }
</style>

{% endblock %}

{% block content %}
<h3>Poster Finals</h3>
<section class="container my-5">
    <div class="table-responsive table_wrapper">
        <table class="table my-1 my-md-2">
            <thead>
                <tr class="text-center">
                    <th scope="col">#</th>
                    <th scope="col">Poster</th>
                    <th scope="col">Student Email id</th>
                    <th scope="col">Uploaded</th>
                    <th scope="col">Score</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for poster in poster %}
                <tr scope="row" class="text-center">
                    <th scope="row">{{forloop.counter}}</th>
                    <td>
                        <a href="{{poster.poster.url}}" class="text-primary" target="_blank"
                            rel="noopener noreferrer">{{poster.poster}}</a>
                    </td>
                    <td>{{poster.student}}</td>
                    <td>{{poster.date_time}}</td>
                    <td>
                        <input type="text" class="form-control" placeholder="Score..." value="{{poster.score}}">
                    </td>
                    <td>
                        <button class="btn btn-success float-left submit_button"
                            data-question="{{poster.id}}">Save</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

{% endblock %}


{% block script %}
<script>
    $(document).ready(function () {

        $(".submit_button").click(function () {
            //Question id
            var q_id = $(this).attr('data-question');
            //answer
            var answer = $(this).parent().prev().children().val();

            if (answer.length == 0) {
                alert("Please fill the answer otherwise you can't go to the next page")
            }
            else {
                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'imageupload:display_poster_finals' %}",
                    type: 'post',
                    data: { 'answer': answer, 'q_id': q_id },
                    dataType: 'json',
                    success: function (data) {
                        if (data['result'] == "Good") {
                            alert("Saved")
                        }
                    }
                });
            }

        });
    });
</script>
{% endblock %}

csevent/templates/imageupload/display_poster_prelims.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Poster Score Page | Prelims</title>
{% endblock %}

{% block head %}

<style>
    .table_wrapper {
        max-height: 450px;
        overflow-y: auto;
        display: inline-block;
    }

    /* Table */
    /* Table Scrollbar Hide */
    .table::-webkit-scrollbar {
        /* Chrome,Edge,Opera,Firefox */
        width: 0px;
        background: transparent;
    }

    .table_wrapper {
        /* Chrome,Edge,Opera,Firefox */
        scrollbar-width: none;
        -ms-overflow-style: none;
    }

    .table_wrapper::-webkit-scrollbar {
        /* Chrome,Edge,Opera,Firefox */
        width: 0px;
    }
</style>

{% endblock %}

{% block content %}
<h3>Poster Prelims</h3>
<section class="container my-5">
    <div class="table-responsive table_wrapper">
        <table class="table my-1 my-md-2">
            <thead>
                <tr class="text-center">
                    <th scope="col">#</th>
                    <th scope="col">Poster</th>
                    <th scope="col">Student Email id</th>
                    <th scope="col">Uploaded</th>
                    <th scope="col">Score</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for poster in poster %}
                <tr scope="row" class="text-center">
                    <th scope="row">{{forloop.counter}}</th>
                    <td>
                        <a href="{{poster.poster.url}}" class="text-primary" target="_blank"
                            rel="noopener noreferrer">{{poster.poster}}</a>
                    </td>
                    <td>{{poster.student}}</td>
                    <td>{{poster.date_time}}</td>
                    <td>
                        <input type="text" class="form-control" placeholder="Score..." value="{{poster.score}}">
                    </td>
                    <td>
                        <button class="btn btn-success float-left submit_button"
                            data-question="{{poster.id}}">Save</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

{% endblock %}


{% block script %}
<script>
    $(document).ready(function () {

        $(".submit_button").click(function () {
            //Question id
            var q_id = $(this).attr('data-question');
            //answer
            var answer = $(this).parent().prev().children().val();
            if (answer.length == 0) {
                alert("Please fill the answer otherwise you can't go to the next page")
            }
            else {
                $.ajax({
                    headers: {
                        "X-CSRFTOKEN": "{{ csrf_token }}",
                        'contentType': 'application/json;charset=utf-8',
                    },
                    url: "{% url 'imageupload:display_poster_prelims' %}",
                    type: 'post',
                    data: { 'answer': answer, 'q_id': q_id },
                    dataType: 'json',
                    success: function (data) {
                        if (data['result'] == "Good") {
                            alert("Saved")
                        }
                    }
                });
            }

        });
    });
</script>
{% endblock %}

csevent/templates/imageupload/logo.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
{% if section %}
<title> Impreza | Round Prelims</title>
{% else %}
<title> Impreza | Round Finals</title>
{% endif %}
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Upload</button>
</form>
{% endblock %}

csevent/templates/imageupload/meta_verify.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
    {% csrf_token %}

</form>
{% endblock %}

csevent/templates/imageupload/poster.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
{% if section %}
<title> Web Dodger | Round Prelims</title>
{% else %}
<title> Web Dodger | Round Finals</title>
{% endif %}
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Upload</button>
</form>
{% endblock %}